# Make the DIV element draggable:

dragElement = (elmnt) ->
  pos1 = 0
  pos2 = 0
  pos3 = 0
  pos4 = 0

  dragMouseDown = (e) ->
    e = e or window.event
    e.preventDefault()
    # get the mouse cursor position at startup:
    pos3 = e.clientX
    pos4 = e.clientY
    document.onmouseup = closeDragElement
    # call a function whenever the cursor moves:
    document.onmousemove = elementDrag
    return

  elementDrag = (e) ->
    e = e or window.event
    e.preventDefault()
    # calculate the new cursor position:
    pos1 = pos3 - (e.clientX)
    pos2 = pos4 - (e.clientY)
    pos3 = e.clientX
    pos4 = e.clientY
    # set the element's new position:
    elmnt.style.top = elmnt.offsetTop - pos2 + 'px'
    elmnt.style.left = elmnt.offsetLeft - pos1 + 'px'
    return

  closeDragElement = ->
    # stop moving when mouse button is released:
    document.onmouseup = null
    document.onmousemove = null
    return

  if document.getElementById(elmnt.id + 'header')
    # if present, the header is where you move the DIV from:
    document.getElementById(elmnt.id + 'header').onmousedown = dragMouseDown
  else
    # otherwise, move the DIV from anywhere inside the DIV:
    elmnt.onmousedown = dragMouseDown
  return

dragElement document.getElementById('mydiv')

# ---
# generated by js2coffee 2.2.0
